server:
  port: 5004

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://postgres:5432/notifications_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
